# We only want to run quarantined tests on main
pr: none
trigger: none

schedules:
- cron: "0 6 * * *"
  displayName: Run tests once a day at 6 AM UTC (10 PM PST)
  branches:
    include:
    - main
  always: true

variables:
- name: _UseHelixOpenQueues
  value: ${{ ne(variables['System.TeamProject'], 'internal') }}
- ${{ if eq(variables['System.TeamProject'], 'internal') }}:
  - group: DotNet-HelixApi-Access

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Helix_quarantined
    jobDisplayName: 'Tests: Helix'
    agentOs: Windows
    installJdk: false
    timeoutInMinutes: 480
    steps:
    - script: ./eng/build.cmd -ci -nobl -all -test -pack -arch x64
              -projects eng\helix\helix.proj /p:RunQuarantinedTests=true /p:IsHelixJob=true
              /p:CrossgenOutput=false /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log
      displayName: Build and run quarantined Helix tests
      continueOnError: true
      env:
        HelixApiAccessToken: $(HelixApiAccessToken) # Needed for internal queues
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    artifacts:
    - name: Helix_logs
      path: artifacts/log/
      publishOnError: true
